service: refunds-data
runtime: python37

basic_scaling:
    max_instances: 2
    idle_timeout: 10m

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10

env_variables:
    BIGQUERY_PROJECT: madecom-dev-tommy-watts
    BUCKET: madecom-dev-tommy-watts-sandbox
